---
name: AppDaemon + CV
version: dev
slug: appdaemon_cv
description: AppDaemon but with OpenCV built-in
webui: http://[HOST]:[PORT:5050]
arch:
  - aarch64
  - amd64
init: false
homeassistant_api: true
uart: true
ports:
  5050/tcp: 5050
ports_description:
  5050/tcp: AppDaemon
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
